@startuml SIA_13_2
package Interface <<Frame>> {
    class Пользователь #PaleGoldenRod ##[dashed]Black {
    {field} cookie
    {method} + Посмотреть свои объявления
    {method} о продаже товаров
    {method} + Посмотреть объявления
    {method} о продаже товаров по запросу
    {method} + Разместить объявление
    {method} о продаже товара
    {method} + Купить товар
    {method} + Оставить отзыв о покупке
    }
}
package System <<Cloud>> {
    class "Информационная система" {
    {method} + Взаимодействие с запросами
    __ protected data __
    {method} # Фронтенд обработчик
    {method} # Бекенд обработчик
    == private data ==
    {method} - Запрос на сервер баз данных
    }
}

package Database <<Database>> {
    class "Сервер баз данных" {
    cookie[] пользователей
    __ protected data __
    {method} # Развернуть бекап
    {method} # Удалить базу
    == private data ==
    {method} - Выполнить SQL запрос
    {method} - Сделать бекап
    }
}

Пользователь -right- "Информационная система"
"Сервер баз данных" <.right. "Информационная система"
@enduml