@startuml SIA_13_PR3_2
participant Seller as S
participant ElectBoard as E
participant Buyer as B
|||
==Размещение товара==
S -> E: Создание объявления \nо продаже товара
S -> E: Указание цены, количества \nи способа связи с Продавцом
hnote across: Объявление становится доступно для просмотра покупателями
==Покупка товара==
B -> E: Поиск товара по запросу
B ->> E: Нахождение товара \nи способа связи с Продавцом
B -> S: Связь с Продавцом \nс целью покупки Товара
B ->> S: Оплата товара
S -->> B: Отправка товара Покупателю
note right: Получение товара
==Завершение работы с Электронной доской объявлений==
B -> E: Написание отзыва о Продавце
S -> E: Удаление объявления \nпри отсутствии товара
@enduml