@startuml SIA_13_PR2_2
left to right direction
skinparam actorStyle awesome
actor Покупатель as br
actor Продавец as sr
rectangle "Электронная доска объявлений" {
    br -- (Просмотр товаров \n по запросу)
    br -- (Купить товар)
    br -- (Оставить отзыв \n о покупке товара)
    (Запрос к \n электронной доске \n объявлений) <|- (Купить товар)
    (Запрос к \n электронной доске \n объявлений) <|- (Оставить отзыв \n о покупке товара)
    (Запрос к \n электронной доске \n объявлений) <|- (Просмотр товаров \n по запросу)
    sr -left- (Просмотр своих товаров)
    sr -- (Высталение товара \n на продажу)
    (Запрос к \n электронной доске \n объявлений) <|-l- (Просмотр своих товаров)
    (Запрос к \n электронной доске \n объявлений)<|-l- (Высталение товара \n на продажу)
    (Запрос к \n электронной доске \n объявлений) -down.> (Проверка авторизации) : <<include>>
    (Анализ ввода для статистики) .up.> (Запрос к \n электронной доске \n объявлений) : <<extend>>
}
@enduml