@startuml SIA_13_PR2_1
|#LightPink|Покупатель|
start
:Запрос страницы;
if (Товар есть в наличии?) is (Нет) then
else (Да)
if (Товар есть в нужном \n количестве?) is (Нет) then
else (Да)
|#LightGreen|Электронная \n доска объявлений|
label auth1;
:**Запрос покупки товара**;
:Отправить запрос в Базу данных;
    |#LightBlue|База данных|
    if (Товар есть в \n Базе данных?) is (да) then
        if (В Базе данных \n есть нужное \n количество товара?) is (да) then
        :Отправить подтверждение \n покупки товара;
        else
        :Вернуть ошибку:\n Отсутствие нужного \n количества товара;
        endif
    else (нет)
    :Вернуть ошибку:\n Отсутствие \n товара;
endif
|#LightGreen|Электронная \n доска объявлений|
if (Покупка успешна) is (да) then
:Уедомление продаца \n о покупке товара;
else (Нет)
:Ошибка 401;
stop
endif
endif
endif
|#LightGreen|Электронная \n доска объявлений|
:**Генерация данных**;
:Передача данных;
:Рендер страницы;
|#LightPink|Покупатель|
:Просмотр страницы;
stop
@enduml